version: "3.9"

services:
  comfyui-docker:
    container_name: comfyui-docker
    restart: unless-stopped
    ports:
      - "8188:8188" # Web UI
    environment:
      - INIT_NODE=${INIT_NODE}
      - UPDATE_NODE=${UPDATE_NODE}
      - INIT_MODEL=${INIT_MODEL}
      - BOOT_CONFIG_INCLUDE=${BOOT_CONFIG_INCLUDE}
      - BOOT_CONFIG_EXCLUDE=${BOOT_CONFIG_EXCLUDE}
      - COMFYUI_EXTRA_ARGS=${COMFYUI_EXTRA_ARGS}
      - HF_API_TOKEN=${HF_API_TOKEN}
      - CIVITAI_API_TOKEN=${CIVITAI_API_TOKEN}
      - CN_NETWORK=${CN_NETWORK}
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - ./comfyui/models:/workspace/ComfyUI/models
      - ./comfyui/output:/workspace/ComfyUI/output
      - ./comfyui/input:/workspace/ComfyUI/input
      - ./comfyui/user:/workspace/ComfyUI/user

    command: >
      bash -c "
        pip install --no-cache-dir --force-reinstall \
          torch==2.8.0+cu128 \
          torchvision==0.23.0+cu128 \
          torchaudio==2.8.0+cu128 \
          xformers==0.0.32.post2 \
          -f https://download.pytorch.org/whl/torch_stable.html &&
        pip install --no-cache-dir piexif soundfile &&
        python main.py --listen 0.0.0.0 --port 8188
      "
